# Create a new docker network or use an existing one

services:
  wordpress:
    container_name: mdatazone_web
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: example_db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - upload_ini:/usr/local/etc/php/conf.d
    depends_on:
      - db
    networks:
      - custom_network

  db:
    container_name: example_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
    networks:
      - custom_network

networks:
  custom_network:
    external: true

volumes:
  wordpress:
  upload_ini:
  db:
