# Create a new docker network or use an existing one

services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.10
    ports:
      - 8080:8080
      - 50051:50051
      - 2112:2112
    volumes:
      - weaviate_data:/var/lib/weaviate
      - weaviate_backup:/home/weaviate_backup
    restart: unless-stopped
    environment:
      IMAGE_INFERENCE_API: "http://i2v-neural:8080"
      OPENAI_APIKEY: ""
      PALM_APIKEY: ""
      QUERY_DEFAULTS_LIMIT: 25
      ASYNC_INDEXING: "true"
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: "KEY1,KEY2"
      AUTHENTICATION_APIKEY_USERS: "USER1,USER2"
      AUTHORIZATION_ADMINLIST_ENABLED: "true"
      AUTHORIZATION_ADMINLIST_USERS: "ADMIN_USER"
      AUTHORIZATION_ADMINLIST_READONLY_USERS: "USER1"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      BACKUP_FILESYSTEM_PATH: "/home/weaviate_backup"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      PROMETHEUS_MONITORING_ENABLED: "true"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai,img2vec-neural,generative-openai,generative-palm,backup-filesystem"
      CLUSTER_HOSTNAME: "node1"

    networks:
      - custom_network
  i2v-neural:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    restart: unless-stopped
    environment:
      ENABLE_CUDA: "0"

    networks:
      - custom_network
volumes:
  weaviate_data:
  weaviate_backup:

networks:
  custom_network:
    external: true
