# Create a new docker network or use an existing one

services:
  squash-tm-pg:
    container_name: squash-tm-pg
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    image: postgres:13
    volumes:
      - squash-db-data:/var/lib/postgresql/data
    networks:
      - custom_network

  squash-tm:
    container_name: squash-tm-app
    depends_on:
      - squash-tm-pg
    environment:
      - SQTM_DB_TYPE=${DB_TYPE}
      - SQTM_DB_USERNAME=${DB_USERNAME}
      - SQTM_DB_PASSWORD=${DB_PASSWORD}
      - SQTM_DB_NAME=${DB_DATABASE}
      - VIRTUAL_HOST=${VH}
    ports:
      - 8080:8080
    image: squashtest/squash-tm
    links:
      - squash-tm-pg:postgres
    volumes:
      - squash-tm-logs:/opt/squash-tm/logs
      - squash-tm-conf:/opt/squash-tm/conf
    networks:
      - custom_network

volumes:
  squash-tm-logs:
  squash-db-data:
  squash-tm-conf:

networks:
  custom_network:
    external: true
